version: '3.8'
services:
  client:
    build:
      context: .
    image: gradlink-client-image:1.0.0
    container_name: gradlink-client-container
    # Map port 8080 on the host to 80 in the container
    ports:
      - "80:80"
    env_file: 
      - .env  # Path to your .env file
    restart: always