name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build locally only for validation (optional)
      # This ensures dist/ is present. 
      - name: Install and Build Locally
        working-directory: server
        run: |
          npm install
          npm run build

      # Prepare minimal deployment package
      - name: Prepare Deployment Package
        working-directory: server
        run: |
          mkdir -p ../deploy-package
          cp -R dist package.json package-lock.json ../deploy-package

      # Deploy the minimal package
      # Without node_modules, Azure will run npm install automatically due to SCM_DO_BUILD_DURING_DEPLOYMENT
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gradlink-server'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy-package